#!/bin/bash

docker build -t testimage .
clear

PYTHON=$(which python)

cat <<EOF >inventory
localhost ansible_python_interpreter=${PYTHON}
EOF

export ANSIBLE_LIBRARY=~/code/ansible-modules-core
ansible-playbook -i ./inventory site.yml $*
