---
- hosts: all
  connection: local
  gather_facts: no
  tasks:

  - include: teardown.yml
    tags: ["present", "started", "reloaded", "restarted", "stopped", "killed", "absent"]

  # STATE: PRESENT

  - include: state-present.yml tags=present
  - include: teardown.yml tags=present

  # STATE: STARTED

  - include: state-started.yml tags=started
  - include: teardown.yml tags=started

  # STATE: RELOADED

  - include: state-reloaded.yml tags=reloaded
  - include: teardown.yml tags=reloaded

  # STATE: RESTARTED

  - include: state-restarted.yml tags=restarted
  - include: teardown.yml tags=restarted

  # STATE: STOPPED

  - include: state-stopped.yml tags=stopped
  - include: teardown.yml tags=stopped

  # STATE: KILLED

  - include: state-killed.yml tags=killed
  - include: teardown.yml tags=killed

  # STATE: ABSENT

  - include: state-absent.yml tags=absent
  - include: teardown.yml tags=absent
